### ISSUE TITLE
Can't migrate settings

### ISSUE THREAD

**Issue by tonypachino** [QuiteRSS/quiterss#1023]
Can you make Quiterss migration better, when i migrating from windows 10 to Linux Ubuntu, i can't migrate my labels and stars, can you fix this in upcoming releases?

**Comment by Katarn** [comment]
How do you use migration at the moment?

**Comment by tonypachino** [comment]
i'm using paths that are under Help - About - Information but still i can't migrate labels and stars.

**Comment by Katarn** [comment]
All labels and stars are in the feeds.db file. This is an SQLite database. Ensure that on all your systems have the same version of QuiteRSS, because different versions can store data about stars and labels in different format. Also make sure that the version of Qt is the same. Recently I found out that the .ini-config from the version of Qt4 is incorrectly read by the version on Qt5, because Qt5 reads the parameters names as register-dependent. (#1028)
