### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by Shardle** [QuiteRSS/quiterss#1167]
QuiteRSS has been great up till today. It crashes around 11 seconds after starting it.
I've tried reinstalling.
When I run it via terminal, I get:

$ quiterss

(quiterss:5105): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(quiterss:5105): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(quiterss:5105): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault

Any ideas what I can do?

**Comment by feed21** [comment]
I have found out that this is an issue from qt5 not from QuiteRSS, a fix has been released and should be in all your repo's soon when you upgrade your distro packages.

Issue reported here: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1833536

Please be patient till the update gets released
You may close this issue here now.
