### ISSUE TITLE
suggestion: allow setting custom user agent

### ISSUE THREAD

**Issue by petermolnar** [QuiteRSS/quiterss#1182]
Tumblr RSS feeds went behind the Oath GDPR wall for Europeans, unless the User Agent contains "Googlebot/" in the string, in which case you get the real RSS feeds.

This obviously shouldn't be in the default User Agent string, but allowing to change it would help some of us regain access to feeds.

**Comment by qcybb** [comment]
Please allow us to change the UserAgent in the config file!

**Comment by Funcy-dcm** [comment]
fix: cf50b74e0f642ac571a348b73905f1bfc7f799e0
Add in the [Settings] group: userAgent = ...

**Comment by TeHMoroS** [comment]
A bit of a necro-bump: if anyone finds that a feed is not working with a warning in the debug.log like so:

`"Parse data error (2): url https://www.baeldung.com/feed/, id 45, line 28, column 7: tag mismatch"`

QuiteRSS uses a user agent string that mimics a web browser. Some feed aggregation services (like FeedBlitz) interpret this as opening a feed in an actual web browser and serve "user friendly" HTML instead of XML. To prevent that, change the user agent string in your config to something non-browser, e.g. `QuiteRSS RSS feed reader (https://quiterss.org/)`.
