### ISSUE TITLE
Version 0.19.0 can't update blog from wordpress.com

### ISSUE THREAD

**Issue by NTsvetkov** [QuiteRSS/quiterss#1202]
Hi,

Version 0.19.0 (15.11.2019)
Revision 3823

It fetched the title without any problems, but when I'm trying to get articles from https://zirakzigil.wordpress.com/rss it says "Connection closed (2)". 

p.s. http:// is not working too.

**Comment by Numbergod** [comment]
Hi Nikolai.  Love the avatar! :-)

![image](https://user-images.githubusercontent.com/6142404/68991650-b9fa7580-08c5-11ea-9507-1c098d62deed.png)

Feed not updating since upgrading to 0.19.0 this morning.
Other feed updating correctly.

If I try requesting via HTTP, I'm getting a 301 redirection to HTTPS and then it appears to fail.

My gut feel is that it's the security certificate or related.

If I put the URL 

https://thebfd.co.nz/feed/

Into Firefox, it returns the correct datastream.

Changing the existing feed URL and trying to add it again as a new feed also fails with the same 299 error.

Tried saving the Cloudflare SSL certificate from Firefox to a .crt file and importing into Win7-64

Appears to have imported and appears to be a valid date range.

Seems unrelated to this...
https://quiterss.org/en/forums/questions/rss-issue-status-server-repied-299

Disabling AVG antivirus makes no difference.

Downgraded to 0.18.12 which is working correctly.
I'm stumped.

**Comment by Funcy-dcm** [comment]
> Hi,
> 
> Version 0.19.0 (15.11.2019)
> Revision 3823
> 
> It fetched the title without any problems, but when I'm trying to get articles from https://zirakzigil.wordpress.com/rss it says "Connection closed (2)".
> 
> p.s. http:// is not working too.

Test: http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by NTsvetkov** [comment]
It works now.

**Comment by Numbergod** [comment]
Working in 0.19.1 

Thanks for fixing it.
Don.
