### ISSUE TITLE
Articles are added again and again with every update

### ISSUE THREAD

**Issue by tnt** [QuiteRSS/quiterss#838]
With version  0.17.7 installed on Fedora from @system/updates I have that problem with this feed:     

  http://feeds.feedburner.com/IT-eBooks?fmt=xml

30 other feeds seem to work fine. And the problem does not occur with Akregator.

**Comment by tnt** [comment]
It turns out that all articles which's `<pubDate>` changes are considered as different (new) articles. 

This means QuiteRSS seems to have no concept of an updated article.

**Comment by Cuelebre** [comment]
I have a similar problem since a clean update to Windows 10, recovering the feeds and the backups. I open the program, delete articles and fully close the program. When I open it again, the deleted articles return to the feeds.
Also I'm getting a lot of SSL certificate errors specially of some Sourceforge feeds, but now always.,

![ssl error 1](https://cloud.githubusercontent.com/assets/4154283/9972883/ba29cc9a-5e6a-11e5-82fa-c2327ca266df.png)
![ssl error 2](https://cloud.githubusercontent.com/assets/4154283/9972882/ba27e2a4-5e6a-11e5-8f1a-a60a461d455d.png)

**Comment by tnt** [comment]
@Cuelebre The certificate issue seems unrelated to me. (Could you maybe fix it by removimg the s from the feeds url - http**s**://feed...? )

When checking the "automatically delete duplicate news"-option in the feed options, the duplicates don't show up.

This seems to have to be done for each and every single feed seperately.
