### ISSUE TITLE
Getting two tray icons in Ubuntu 15.10

### ISSUE THREAD

**Issue by ed-torvalds** [QuiteRSS/quiterss#852]
I am using QuiteRss v 0.18.2. I am getting two tray icons on Ubuntu 15.10. Note other programs don't have this problem.
Second problem is your ppa is not working for this version of Ubuntu
Thanks for your software
Cheers

**Comment by ghost** [comment]
Same here.

**Comment by qazip** [comment]
I'm having this issue on Ubuntu 16.04, QuiteRSS version 0.18.3..

Will this not be fixed?

**Comment by twentyonethirty** [comment]
the bug is still persist, but you always can roll-back changes to previous version
you need do following:
1. apt-get remove quiterss
2. wget http://mirrors.xmission.com/ubuntu/pool/universe/q/quiterss/quiterss_0.13.3+dfsg-2_amd64.deb
3. dpkg -i quiterss_0.13.3+dfsg-2_amd64.deb
4. apt-mark hold quiterss

**Comment by Funcy-dcm** [comment]
Try 0.18.6
