### ISSUE TITLE
Loading Feeds with Previously Deleted Items

### ISSUE THREAD

**Issue by dave47** [QuiteRSS/quiterss#974]
When I delete items from a feed I do not want them reloaded again.  That's like chasing your tail.

**Comment by Katarn** [comment]
Do you use database cleanup? Or give an example of a feed, maybe it's incorrect.

**Comment by dave47** [comment]
I am using the cleanup button.  Feeds

http://www.majorgeeks.com/files/rss
http://feeds.feedburner.com/filehippo

**Comment by Katarn** [comment]
> I am using the cleanup button.

In this dialog window, bottom checkbox deepy clears the database, including information about deleted news. That's why they are loaded again. If you have deleted 10,000 entries in the separated feed, this checkbox will finally remove them from the database (pressing Delete button just marks them as deleted, but not really delete). It's okay if the last 20-30 news are loaded in each feed again.

Just uncheck the bottom checkbox. Use it once, every six months or a year to reduce the size of the database file. In other cases, its use is unreasonable.

**Comment by Funcy-dcm** [comment]
Send screenshots
